import math
a = int(input("a: "))
b = int(input("b: "))
print("The sum of a and b: " + str(a+b))
print("The difference when b is subtracted from a: " + str(b-a))
print("The product of a and b: " + str(a*b))
print("The quotient when a is divided by b: " + str(a/b))
print("The remainder when a is divided by b: " + str(a % b))
print("The result of log10 a: " + str(math.log10(a)))
print("The result of ab: " + str(a) + str(b))
